<a href="https://colab.research.google.com/github/PatchareepornT/Basicprg_DataViz65/blob/main/recap_4_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Slicing

In [ ]:
import numpy

In [ ]:
list_a = [[2,4,5],[1,2,3],[9,8,7],[3,6,9]]
mat_a = numpy.array(list_a)
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [ ]:
import numpy as np

In [ ]:
list_b = [[-1,-1,2,4,5],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_b = np.array(list_b)
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

#Quiz2

1. slice ค่าลบออกมาจาก mat_b
2. slice [1,2,3] จาก mat_a
3. slice [[1,3],[9,7],[3,9]] ออกมาจาก mat_b

In [ ]:
#ข้อ1
mat_b[:5,:2]

array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

In [ ]:
#ข้อ2
mat_a[1:2,:4]

array([[1, 2, 3]])

In [ ]:
#ข้อ3
mat_b[1:4,2:5:2]

array([[1, 3],
       [9, 7],
       [3, 9]])

#Quiz3

เขียน function แสดงความต่างของเวลาโดย input อยู่ในรูปแบบ 'XX:YY:ZZ - AA:BB:CC'

และวนลูปแสดงผลของ input ต่อไปนี้

'09:11:50 - 12:30:15'

'13:41:07 - 20:00:18'

'00:00:00 - 23:59:59'

'18:04:11 - 00:00:00'

'21:30:00 - 03:05:15'

ตัวอย่าง input '00:00:00-01:00:00'

output ช่วงระยะเวลาระหว่าง 00:00:00 ถึง 01:00:00 มีเวลาทั้งหมด 3,600 วินาที

In [1]:
def print_time(alltime): #mytime = input
    for i in (alltime):
      start=alltime.split("-") 
      time1=start[0] 
      sp_time1=time1.split(":") 
      time2=start[1] 
      sp_time2=time2.split(":") 
      x1 = (int(sp_time1[0])*3600)+(int(sp_time1[1])*60)+int(sp_time1[2])
      x2 = (int(sp_time2[0])*3600)+(int(sp_time2[1])*60)+int(sp_time2[2])
      time3 = x2-x1
      time1day = 86400 
    if time3 < 0 :
       time4 = (time3 + time1day)
       print(f'ช่วงระยะเวลาระหว่าง {time1}ถึง{time2} มีเวลาทั้งหมด {time4:,} วินาที')
    else:
      print(f'ช่วงระยะเวลาระหว่าง {time1}ถึง{time2} มีเวลาทั้งหมด {time3:,} วินาที')

In [3]:
print_time('09:11:50 - 12:30:15')

ช่วงระยะเวลาระหว่าง 09:11:50 ถึง 12:30:15 มีเวลาทั้งหมด 11,905 วินาที


In [4]:
print_time('13:41:07 - 20:00:18')

ช่วงระยะเวลาระหว่าง 13:41:07 ถึง 20:00:18 มีเวลาทั้งหมด 22,751 วินาที


In [5]:
print_time('00:00:00 - 23:59:59')

ช่วงระยะเวลาระหว่าง 00:00:00 ถึง 23:59:59 มีเวลาทั้งหมด 86,399 วินาที


In [6]:
print_time('18:04:11 - 00:00:00')

ช่วงระยะเวลาระหว่าง 18:04:11 ถึง 00:00:00 มีเวลาทั้งหมด 21,349 วินาที


In [7]:
print_time('21:30:00 - 03:05:15')

ช่วงระยะเวลาระหว่าง 21:30:00 ถึง 03:05:15 มีเวลาทั้งหมด 20,115 วินาที
